In [9]:
import pandas as pd
import numpy as np

# load cleaned data
df = pd.read_csv('../clean/goncalo_clean.csv')

# safety copy
df = df.copy()

df.head()

   runtime  popularity  vote_average  popularity_log
0    162.0  150.437577           7.2        5.020174
1    169.0  139.082615           6.9        4.942232
2    148.0  107.376788           6.3        4.685614
3    165.0  112.312950           7.6        4.730153
4    132.0   43.926995           6.1        3.805039

The goal of this step is to create new features that better capture patterns in the data and improve the model’s ability to predict movie popularity.

In [10]:
df['popularity_log'] = np.log1p(df['popularity'])

In [11]:
df['runtime_category'] = pd.cut(
    df['runtime'],
    bins=[0, 90, 120, 150, 240],
    labels=['Short', 'Standard', 'Long', 'Very Long']
)

In [12]:
df['runtime_squared'] = df['runtime'] ** 2

In [13]:
df['runtime_x_rating'] = df['runtime'] * df['vote_average']

In [14]:
df['rating_category'] = pd.cut(
    df['vote_average'],
    bins=[0, 5, 6.5, 8, 10],
    labels=['Low', 'Average', 'Good', 'Excellent']
)

In [15]:
df.head()
df.describe()

,runtime,popularity,vote_average,popularity_log,runtime_squared,runtime_x_rating
count,4675.000000,4675.000000,4675.000000,4675.000000,4675.000000,4675.000000
mean,107.055187,21.728483,6.107465,2.545200,11776.344171,661.030717
std,17.765094,31.937289,1.123605,1.140138,4146.930507,189.657287
min,76.000000,0.000372,0.000000,0.000372,5776.000000,0.000000
25%,94.000000,5.000313,5.600000,1.791812,8836.000000,540.600000
50%,104.000000,13.308127,6.200000,2.660828,10816.000000,646.400000
75%,117.000000,28.609656,6.800000,3.388101,13689.000000,767.000000
max,178.000000,875.581305,10.000000,6.776029,31684.000000,1470.000000

Several features were engineered to improve the model’s predictive power. A log transformation was applied to the popularity variable to reduce skewness and stabilize variance. Polynomial and interaction features were created to capture non-linear relationships between runtime and popularity, as well as the combined effect of runtime and movie ratings. Additionally, runtime and rating were grouped into categories to help the model capture broader patterns that may not be reflected in raw numerical values.